project:
  type: website

website:
  title: "get sh*t done - the blog"
  site-url: https://blog.frieder-rodewald.de
  description: "a project aimed to get sh*t done"

  navbar:
    search: true

  page-footer:
    left: 'by <a href="https://frieder-rodewald.de/">Frieder Rodewald</a>'
    right:
      - icon: github
        href: https://github.com/FriederRodewald
      - icon: rss
        href: index.xml
format:
  html:
    pagetitle: "blog > get sh*t done - {{< meta title >}}"
    theme: style.scss
    code-link: true
    code-fold: true
    code-tools:
      toggle: true
      source: false
